name: BuildAndLint

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:
    name: BuildCheck
    runs-on: ubuntu-latest
    steps:
      - name: Install Dynamixel SDK
        run: |
          cd ..
          git clone https://github.com/ROBOTIS-GIT/DynamixelSDK.git
          cd DynamixelSDK/c/build/linux64
          make
          sudo make install
      - uses: actions/checkout@v2
      - name: Build files
        run: |
          for a in `find . -name Makefile`;do cd `dirname $a` && make && cd -; done

  lint:
    name: Lint
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Install cpplint
        run: |
          python -m pip install --upgrade pip
          pip install --user cpplint
      - uses: actions/checkout@v2
      - name: Lint with cpplint
        run: |
          cpplint --filter=-whitespace,-build `find . -name "*.[ch]"`
